name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/'
  pull_request:
    paths-ignore:
      - 'docs/'
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Inclure les tests et l’analyse statique ?'
        required: true
        default: true
        type: boolean

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true'
        run: pnpm run type-check

      - name: Lint
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true'
        run: pnpm run lint

      - name: Test
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_tests == 'true'
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/
          retention-days: ${{ github.ref == 'refs/heads/main' && 7 || 1 }}

  deploy:
    name: Deploy to QA and PROD
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Deploy to QA
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_QA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"

      - name: Deploy to PROD
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist"